<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config["google_key"] = 'AIzaSyCJ7btx16PBtyLAhgSQVyTze6f78GUXy0k';
$config["REMOTE_SOCKET_GOOGLE"] = 'https://android.googleapis.com/gcm/send';
$config["PASS_PHRASE"] = "12345678";
$config["REMOTE_SOCKET_APPLE"] = 'ssl://gateway.push.apple.com:2195';
$config['pagination_limit'] = 10;
$config["pem_en"] = "ck_dist_en.pem";
$config["pem_ar"] = "ck_dist_ar.pem";
$config["instagram_client"] = "20fedafd752f4516995ec9c50027a41b";
$config["instagram_secret"] = "e5bbf066b12e44cea3d00b1e00c25643";
$config["club_apiKey"] = "vg8rt93ff0q";
$config["club_availability_url"] = "https://cdn.nonweiler.com/tcad/availability";
$config["club_reservation_url"] = "https://cdn.nonweiler.com/tcad/reservation";
$config["club_authentication_url"] = "https://cdn.nonweiler.com/tcad/authenticate";